[package]
name = "arsenal"
version = "0.1.0"
authors = ["Zicklag <zicklag@katharostech.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]

    [dependencies.pyo3]
    version = "0.7.0"
    features = ["extension-module"]
